### PR TITLE
Allow users to choose migration table

### PR DESCRIPTION
**Pull request by JulienTant**
The goal of this PR is to allow users to choose the name of the table used to store migration.

### CODE REVIEW

**Comment by JulienTant** [comment]
TravisCI act strangely, it looses network on some build (before ours tests are executed), but if you look at the details you see that those which reaches the tests pass successfully.

**Comment by byjg** [comment]
Hello,

Thank you for your PR. I'll take a look today later. Meanwhile, could you explain the motivation for you want to choose the name of the migration table? I am just ask this because this table is used only for internal purposes and do not affect directly your app.

**Comment by JulienTant** [comment]
Hi,

tl;dr: we want each microservices which shares a schema to manage its own migrations.

We have a huge MySQL server for our application which is shared between many microservices. We have one schema by "Domain" but some domains can contains many microservices. For now, each domain has a microservices responsible for dealing with all migrations of the domain, but we want to change that so that each microservices is independant in term of managing its tables.

**Comment by byjg** [comment]
OK. It is far enough. But are you conscious that it can to create a big side effect in your migration? Here some I can figure out right now:
- If someone apply scripts for the same table it could mess all your migration and live data. 
- if someone for some remote reason forget to pass the migration table parameter you simply can lose all your work. 

I'll go into detail of your PR later.

**Comment by JulienTant** [comment]
Thanks for the warning!

We're using the package programmatically, not by using the cli tool. Each microservices launch its migrations when it starts, so the parameter will never be forgotten. No decision have been taken yet about where to store the name of the table, but I will push to have it hardcoded to make us safe.

**Comment by byjg** [comment]
Hello Julien, 

I merged this feature inside the branch 2.1.0. It will be there for a while. Right now, If you can use this version you can do:

```json
{
   "minumum-stability": "dev"
   "require": {
      "byjg/migration": "2.1.0.x-dev"
   }
}
```

Or you can use the mask "2.1.*"

I dropped the support for this feature on the command line. 

Thank you for your Pull Request ;)

**Pull request merged**
